#include "localization_keys.hpp"

namespace overlay::loc
{
    std::span<const Key> Inventory() noexcept
    {
        using namespace loc;
        static constexpr Key keys[] = {
            app::Title,
            common::Enabled, common::Disabled, common::Unavailable,
            common::UnavailableValue, common::CannotAssess, common::Active,
            common::Ready, common::Applying, common::Starting, common::Ending,
            common::Waiting, common::Applied, common::Pending, common::Error,
            common::Yes, common::No, common::Examples,
            section::RuntimeSettings, section::CameraTransition, section::Gameplay,
            section::Cinematics, section::Dialogue, section::Overlay, section::Hotkeys,
            section::Runtime, section::CameraIntegration, section::CameraState,
            section::Presentation, section::Zoom, section::Fov, section::Sources,
            section::Generation,
            ui::ViewportAspect,
            setting::GameplayMode, setting::CinematicAspect, setting::CinematicFov,
            setting::DialogueZoom, setting::OverlayToggle, setting::Language,
            setting::FontSize,
            setting::Mode, setting::AspectRatio, setting::FovMode, setting::Zoom,
            notice::MouseCapture,
            rebind::PressKey,
            transition::Waiting, transition::Aligned, transition::NotAligned,
            transition::DetailWaiting, transition::DetailAligned,
            transition::DetailNotAligned, transition::DetailCannotAssess,
            transition::ActiveValue,
            status::GameplayIncomplete, status::GameplayHookUnavailable,
            status::CameraUpdateWaiting, status::NativeRecalculationPersists,
            status::GameplayDisabled, status::GameplayContextUnavailable,
            status::HorPlusWaiting, status::HorPlusActive,
            status::NativeRecalculationEnabled, status::CinematicIncomplete,
            status::CinematicUnavailable, status::CinematicNativeReady,
            status::NextCinematicReady, status::CinematicActive,
            status::CinematicSelectionIncomplete,
            status::DialogueIncomplete, status::DialogueHookUnavailable,
            status::DialogueCapabilityUnavailable, status::DialogueModeUnavailable,
            status::DialogueNativeReady, status::DialogueAdaptiveReady,
            status::DialogueReducedReady, status::DialogueDisabledReady,
            status::DialogueReady, status::DialogueActive, status::DialogueStarting,
            status::ActiveDialoguePolicyUnavailable, status::DialogueEnding,
            status::DialogueRecoveryWaiting, status::DialogueStateUnknown,
            status::RuntimeUnavailable,
            tooltip::gameplay::Enabled, tooltip::gameplay::Disabled,
            tooltip::gameplay::HorPlus,
            tooltip::gameplay::HorPlusExamplesContext,
            tooltip::gameplay::HorPlusExample90,
            tooltip::gameplay::HorPlusExample100,
            tooltip::gameplay::HorPlusExample110,
            tooltip::gameplay::AspectRecalculation,
            tooltip::cinematics::AspectAuto, tooltip::cinematics::AspectNative,
            tooltip::cinematics::Aspect169, tooltip::cinematics::Aspect219,
            tooltip::cinematics::Aspect329,
            tooltip::cinematics::AspectForcedExample,
            tooltip::cinematics::FovGameplay,
            tooltip::cinematics::FovGameplayExamplesContext,
            tooltip::cinematics::FovGameplayExample90,
            tooltip::cinematics::FovGameplayExample112_6,
            tooltip::cinematics::FovNative,
            tooltip::cinematics::FovNativeExamplesContext,
            tooltip::cinematics::FovNativeExample90,
            tooltip::dialogue::ZoomNative, tooltip::dialogue::ZoomAdaptive,
            tooltip::dialogue::ZoomExamplesContext,
            tooltip::dialogue::ZoomNativeExample90,
            tooltip::dialogue::ZoomNativeExample110,
            tooltip::dialogue::ZoomAdaptiveExample90,
            tooltip::dialogue::ZoomAdaptiveExample110,
            tooltip::dialogue::ZoomReduced, tooltip::dialogue::ZoomReducedExample90,
            tooltip::dialogue::ZoomReducedExample110,
            tooltip::dialogue::ZoomDisabled,
            tooltip::dialogue::ZoomDisabledExample90,
            tooltip::dialogue::ZoomDisabledExample110,
            tooltip::hotkeys::Enabled, tooltip::hotkeys::Disabled,
            tooltip::hotkeys::Change, tooltip::hotkeys::ChangeOverlay,
            tooltip::hotkeys::SingleKey, tooltip::hotkeys::Rebind,
            tooltip::hotkeys::GameplayCycle,
            tooltip::hotkeys::CinematicAspectCycle,
            tooltip::hotkeys::CinematicFovCycle, tooltip::hotkeys::DialogueCycle,
            tooltip::overlay::AlwaysActive,
            tooltip::runtime::Viewport, tooltip::runtime::ViewportAuto,
            tooltip::runtime::ViewportUnavailable, tooltip::runtime::AspectMatched,
            tooltip::runtime::AspectMismatch, tooltip::runtime::AspectCannotAssess,
            tooltip::runtime::CinematicAspect,
            tooltip::runtime::CinematicAspectUnavailable,
            tooltip::runtime::GameplayFov, tooltip::runtime::GameplayFovUnavailable,
            tooltip::runtime::NativeFov, tooltip::runtime::NativeFovUnavailable,
            tooltip::runtime::HorPlusFov, tooltip::runtime::HorPlusFovUnavailable,
            camera_state::Waiting, camera_state::State, camera_state::GameplayFov, camera_state::Provenance,
            camera_state::Epoch, camera_state::Mode, camera_state::Valid,
            camera_state::Direction, camera_state::Active,
            camera_state::EvidenceValid, camera_state::Sequence,
            camera_state::Primary, camera_state::Secondary, camera_state::Source,
            camera_state::Confidence, camera_state::PolicyValid,
            camera_state::RecoveryExcluded, camera_state::Target,
            camera_state::SettingKnown, camera_state::GameSource,
            camera_state::Native, camera_state::NativeSource,
            camera_state::HorPlus, camera_state::HorPlusSource,
            camera_state::Aspect, camera_state::AspectSource, camera_state::Flags,
            camera_state::GameplayWriter, camera_state::PresentationEpoch,
            camera_state::EventSequence, camera_state::UnavailableCounter,
            notification::HotkeyConflict, notification::HotkeyTitle,
            notification::BindingValue, notification::ConflictValue,
            notification::SettingChanged, notification::OpenOverlayHint,
        };
        return keys;
    }
}
